import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  researchSidebar: [
    {type: 'doc', id: 'VISION', label: 'Vision'},
    {
      type: 'link',
      label: 'Principle catalog',
      href: '/principles',
    },
    {
      type: 'category',
      label: 'Research notebook',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'research'}],
    },
  ],
};

export default sidebars;
